import os
import sqlite3
import hashlib
import secrets
from datetime import datetime, date
from urllib.parse import quote_plus

from flask import Flask, render_template, request, redirect, url_for, session, flash, send_from_directory
from werkzeug.utils import secure_filename

BASE = os.path.dirname(os.path.abspath(__file__))
SQLITE_DB = os.path.join(BASE, 'wodashtech.db')
UPLOADS = os.path.join(BASE, 'uploads')
os.makedirs(UPLOADS, exist_ok=True)

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', secrets.token_hex(32))
app.config['MAX_CONTENT_LENGTH'] = 25 * 1024 * 1024

# Render sets DATABASE_URL when the web service is connected to Render Postgres.
# SQLite remains available for local development.
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

CONTENT_ITEMS = [
    'CHLORINATION OF WATER', 'EUCLIDEN DISTANCE', 'GAUSS, ein UMIRIS',
    'GEOMETRY FOUNDATION IN TECH', 'HISTORY OF CHEMISTRY VOLUME 1',
    'HISTORY OF CHEMISTRY VOLUME 2', 'HISTORY OF CHEMISTRY VOLUME 3',
    'HISTORY OF CHEMISTRY VOLUME 4', 'HISTORY OF IT', 'History of AI Models',
    'History of TECHNOLOGY SCIENCE', 'Algorithms & INVENTIONS',
    'Machine Learning', 'Deep Learning', 'Graphics', 'Simulations',
    'Probabilities in TECH'
]
TAGS = ['AI Models', 'Machine Learning', 'Algorithms', 'Deep Learning', 'Simulations', 'Data', 'Signal', 'Robotics', 'Game']
ALLOWED = {'pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif'}

SCHEMA = '''
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    birthday TEXT NOT NULL,
    age INTEGER NOT NULL,
    created TEXT NOT NULL,
    last_login TEXT
);
CREATE TABLE IF NOT EXISTS documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    stored_name TEXT NOT NULL,
    original_name TEXT NOT NULL,
    uploaded TEXT NOT NULL,
    size INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
'''


def is_postgres():
    return bool(DATABASE_URL)


def pg_url():
    # Some providers still return postgres://. psycopg accepts postgresql://.
    return DATABASE_URL.replace('postgres://', 'postgresql://', 1)


def db():
    if not is_postgres():
        con = sqlite3.connect(SQLITE_DB)
        con.row_factory = sqlite3.Row
        return con

    import psycopg
    from psycopg.rows import dict_row
    con = psycopg.connect(pg_url(), row_factory=dict_row)
    return con


def execute_schema(con):
    if not is_postgres():
        con.executescript(SCHEMA)
        return

    # PostgreSQL uses GENERATED identity columns rather than SQLite's AUTOINCREMENT.
    con.execute('''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            first_name TEXT NOT NULL,
            last_name TEXT NOT NULL,
            birthday TEXT NOT NULL,
            age INTEGER NOT NULL,
            created TEXT NOT NULL,
            last_login TEXT
        )
    ''')
    con.execute('''
        CREATE TABLE IF NOT EXISTS documents (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            stored_name TEXT NOT NULL,
            original_name TEXT NOT NULL,
            uploaded TEXT NOT NULL,
            size INTEGER NOT NULL
        )
    ''')


def init_db():
    con = db()
    execute_schema(con)
    con.commit()
    con.close()


init_db()


def hash_password(password):
    # PBKDF2 is intentionally used instead of a single fast SHA-256 hash.
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 310_000)
    return 'pbkdf2_sha256$310000$' + salt.hex() + '$' + digest.hex()


def verify_password(password, stored):
    try:
        algorithm, iterations, salt_hex, digest_hex = stored.split('$')
        if algorithm != 'pbkdf2_sha256':
            return False
        digest = hashlib.pbkdf2_hmac('sha256', password.encode(), bytes.fromhex(salt_hex), int(iterations))
        return secrets.compare_digest(digest.hex(), digest_hex)
    except (ValueError, TypeError):
        return False


def age_from_birth(b):
    today = date.today()
    return today.year - b.year - ((today.month, today.day) < (b.month, b.day))


def current_user():
    if 'user_id' not in session:
        return None
    con = db()
    u = con.execute('SELECT * FROM users WHERE id=%s' if is_postgres() else 'SELECT * FROM users WHERE id=?', (session['user_id'],)).fetchone()
    con.close()
    return u


def logged_in():
    return current_user() is not None


@app.context_processor
def inject():
    return {'user': current_user(), 'tags': TAGS}


@app.route('/')
def index():
    return redirect(url_for('dashboard') if logged_in() else url_for('login'))


@app.route('/health')
def health():
    return {'status': 'ok', 'database': 'postgresql' if is_postgres() else 'sqlite'}


@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email', '').strip().lower()
        password = request.form.get('password', '')
        con = db()
        u = con.execute('SELECT * FROM users WHERE email=%s' if is_postgres() else 'SELECT * FROM users WHERE email=?', (email,)).fetchone()
        if not u or not verify_password(password, u['password']):
            con.close()
            flash('Account not found or incorrect password.', 'error')
            return redirect(url_for('login'))
        con.execute('UPDATE users SET last_login=%s WHERE id=%s' if is_postgres() else 'UPDATE users SET last_login=? WHERE id=?',
                     (datetime.now().isoformat(timespec='seconds'), u['id']))
        con.commit()
        con.close()
        session['user_id'] = u['id']
        session.permanent = bool(request.form.get('remember'))
        return redirect(url_for('dashboard'))
    return render_template('login.html')


@app.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        first = request.form.get('first_name', '').strip()
        last = request.form.get('last_name', '').strip()
        birthday = request.form.get('birthday', '').strip()
        email = request.form.get('email', '').strip().lower()
        password = request.form.get('password', '')
        confirm = request.form.get('confirm_password', request.form.get('confirm', ''))
        if len(first) < 2 or len(last) < 2 or not first.replace(' ', '').isalpha() or not last.replace(' ', '').isalpha():
            flash('Enter valid first and last names.', 'error')
            return render_template('signup.html')
        try:
            b = date.fromisoformat(birthday)
        except ValueError:
            flash('Enter a valid birth date.', 'error')
            return render_template('signup.html')
        age = age_from_birth(b)
        if age < 13:
            flash('You must be at least 13 years old.', 'error')
            return render_template('signup.html')
        if age > 120:
            flash('Please enter a valid birth date.', 'error')
            return render_template('signup.html')
        if '@' not in email or '.' not in email.split('@')[-1]:
            flash('Enter a valid email address.', 'error')
            return render_template('signup.html')
        if len(password) < 8:
            flash('Password must be at least 8 characters.', 'error')
            return render_template('signup.html')
        if password != confirm:
            flash('Passwords do not match.', 'error')
            return render_template('signup.html')

        con = db()
        try:
            if is_postgres():
                cur = con.execute('''INSERT INTO users(email,password,first_name,last_name,birthday,age,created)
                                     VALUES(%s,%s,%s,%s,%s,%s,%s) RETURNING id''',
                                  (email, hash_password(password), first, last, birthday, age,
                                   datetime.now().isoformat(timespec='seconds')))
                user_id = cur.fetchone()['id']
            else:
                cur = con.execute('''INSERT INTO users(email,password,first_name,last_name,birthday,age,created)
                                     VALUES(?,?,?,?,?,?,?)''',
                                  (email, hash_password(password), first, last, birthday, age,
                                   datetime.now().isoformat(timespec='seconds')))
                user_id = cur.lastrowid
            con.commit()
            session['user_id'] = user_id
        except Exception as exc:
            con.rollback()
            con.close()
            if 'unique' in str(exc).lower() or 'duplicate' in str(exc).lower():
                flash('An account with that email already exists.', 'error')
                return render_template('signup.html')
            raise
        con.close()
        return redirect(url_for('welcome'))
    return render_template('signup.html')


@app.route('/welcome')
def welcome():
    if not logged_in():
        return redirect(url_for('login'))
    return render_template('welcome.html')


@app.route('/dashboard')
def dashboard():
    if not logged_in():
        return redirect(url_for('login'))
    q = request.args.get('q', '').strip()
    items = [x for x in CONTENT_ITEMS if q.lower() in x.lower()] if q else CONTENT_ITEMS
    u = current_user()
    con = db()
    docs = con.execute('SELECT * FROM documents WHERE user_id=%s ORDER BY id DESC' if is_postgres() else 'SELECT * FROM documents WHERE user_id=? ORDER BY id DESC', (u['id'],)).fetchall()
    con.close()
    return render_template('dashboard.html', items=items, query=q, docs=docs)


@app.route('/upload', methods=['POST'])
def upload():
    u = current_user()
    if not u:
        return redirect(url_for('login'))
    f = request.files.get('document')
    if not f or not f.filename:
        flash('Choose a document first.', 'error')
        return redirect(url_for('dashboard'))
    ext = f.filename.rsplit('.', 1)[-1].lower() if '.' in f.filename else ''
    if ext not in ALLOWED:
        flash('File type is not supported.', 'error')
        return redirect(url_for('dashboard'))
    original = secure_filename(f.filename)
    stored = f'{secrets.token_hex(12)}_{original}'
    path = os.path.join(UPLOADS, stored)
    f.save(path)
    con = db()
    con.execute('INSERT INTO documents(user_id,stored_name,original_name,uploaded,size) VALUES(%s,%s,%s,%s,%s)' if is_postgres() else
                'INSERT INTO documents(user_id,stored_name,original_name,uploaded,size) VALUES(?,?,?,?,?)',
                (u['id'], stored, original, datetime.now().isoformat(timespec='seconds'), os.path.getsize(path)))
    con.commit()
    con.close()
    flash('Document uploaded successfully.', 'success')
    return redirect(url_for('dashboard'))


@app.route('/uploads/<path:name>')
def uploads(name):
    u = current_user()
    if not u:
        return redirect(url_for('login'))
    con = db()
    d = con.execute('SELECT * FROM documents WHERE stored_name=%s AND user_id=%s' if is_postgres() else
                    'SELECT * FROM documents WHERE stored_name=? AND user_id=?', (name, u['id'])).fetchone()
    con.close()
    if not d:
        return ('Not found', 404)
    return send_from_directory(UPLOADS, name, as_attachment=False)


@app.route('/delete/<int:doc_id>', methods=['POST'])
def delete(doc_id):
    u = current_user()
    if not u:
        return redirect(url_for('login'))
    con = db()
    d = con.execute('SELECT * FROM documents WHERE id=%s AND user_id=%s' if is_postgres() else
                    'SELECT * FROM documents WHERE id=? AND user_id=?', (doc_id, u['id'])).fetchone()
    if d:
        path = os.path.join(UPLOADS, d['stored_name'])
        if os.path.exists(path):
            os.remove(path)
        con.execute('DELETE FROM documents WHERE id=%s' if is_postgres() else 'DELETE FROM documents WHERE id=?', (doc_id,))
        con.commit()
        flash('Document deleted.', 'success')
    con.close()
    return redirect(url_for('dashboard'))


@app.route('/ramus')
def ramus():
    q = request.args.get('q', '').strip()
    return redirect('https://www.google.com/search?q=' + quote_plus(q) if q else url_for('dashboard'))


@app.route('/reset', methods=['GET', 'POST'])
def reset():
    if request.method == 'POST':
        email = request.form.get('email', '').strip().lower()
        con = db()
        u = con.execute('SELECT id FROM users WHERE email=%s' if is_postgres() else 'SELECT id FROM users WHERE email=?', (email,)).fetchone()
        con.close()
        # Email delivery is intentionally not enabled until an SMTP/provider is configured.
        if u:
            flash('If the account exists, reset instructions would be sent to the email address.', 'success')
        else:
            flash('Account not found.', 'error')
        return redirect(url_for('reset'))
    return render_template('reset.html')


@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('login'))


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)), debug=False)
